'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { Container } from '@/components/layout/container';
import { ProductForm } from '@/components/product/product-form';
import { Card } from '@/components/ui/card';
import { productApi } from '@/lib/api/products';
import { categoryApi } from '@/lib/api/categories';
import { Category } from '@/lib/types/category';

export default function CreateProductPage() {
  const router = useRouter();
  const [categories, setCategories] = useState<Category[]>([]);

  useEffect(() => {
    async function fetchCategories() {
      try {
        const data = await categoryApi.getCategories();
        setCategories(data);
      } catch (err) {
        console.error('Failed to load categories:', err);
      }
    }
    fetchCategories();
  }, []);

  const handleSubmit = async (formData: {
    name: string;
    description: string;
    price: string;
    category: string;
    imageFile: File | null;
  }) => {
    try {
      // Find the category ID from the selected category name
      const selectedCategory = categories.find(cat => cat.name === formData.category);
      
      if (!selectedCategory) {
        throw new Error('Selected category not found');
      }

      const categoryIds = [selectedCategory.id];

      // Transform form data to match Product interface
      const productData = {
        name: formData.name,
        description: formData.description,
        price: Number.parseFloat(formData.price),
        sku: '', // SKU will be auto-generated by backend
        categoryIds,
      };

      // Call API to create product
      const createdProduct = await productApi.createProduct(productData);

      // Upload image if provided
      if (formData.imageFile && createdProduct.id) {
        try {
          const imageFormData = new FormData();
          imageFormData.append('file', formData.imageFile);

          const response = await fetch(`/api/products/${createdProduct.id}/images`, {
            method: 'POST',
            body: imageFormData,
          });

          if (!response.ok) {
            console.error('Failed to upload image:', await response.text());
          }
        } catch (err) {
          console.error('Failed to upload image:', err);
          // Continue anyway - product was created successfully
        }
      }

      // Redirect to product detail page after successful creation
      setTimeout(() => {
        router.push(`/products/${createdProduct.id}`);
      }, 1500);
    } catch (error) {
      // Re-throw the error so ProductForm can display it
      console.error('Error creating product:', error);
      throw error;
    }
  };

  return (
    <Container>
      <div className="py-8">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-slate-900">Create New Product</h1>
          <p className="mt-2 text-slate-600">
            Add a new product to your inventory
          </p>
        </div>

        <Card className="p-6">
          <ProductForm onSubmit={handleSubmit} />
        </Card>
      </div>
    </Container>
  );
}
